# Generated by Django 4.0 on 2021-12-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='quiz',
            field=models.JSONField(null=True),
        ),
    ]
